[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["npm ci --prefer-offline --no-audit --progress=false"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx serve dist -s -l $PORT"
